status = [
    'linter-check',
    'phpstan-tests',
    'integration-tests (PHP 7.4)',
    'integration-tests (PHP 8.0)',
    'integration-tests (PHP 8.1)',
    'integration-tests (PHP 8.2)'
]
# 1 hour timeout
timeout-sec = 3600
